find_path(LIBSURFER_INCLUDE_DIR surface_generator.hh
  PATHS ${LIBSURFER_FOLDER}
  PATH_SUFFIXES src
  )

find_library(LIBSURFER_LIBRARY libLibSurfer.so
  PATHS ${LIBSURFER_BINARIES}
  PATH_SUFFIXES src
  )

find_package(FFTW REQUIRED)

#===============================================================================
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LIBSURFER DEFAULT_MSG
  LIBSURFER_LIBRARY LIBSURFER_INCLUDE_DIR)

mark_as_advanced(LIBSURFER_LIBRARY LIBSURFER_INCLUDE_DIR)

set(LIBSURFER_LIBRARIES_ALL ${LIBSURFER_LIBRARY} ${FFTW_LIBRARIES} ${FFTW_THREAD_LIBRARY} ${FFTW_OPENMP_LIBRARY})
set(LIBSURFER_LIBRARIES ${LIBSURFER_LIBRARIES_ALL} CACHE INTERNAL "Libraries for LibSurfer" FORCE)
set(LIBSURFER_INCLUDE_DIRS ${LIBSURFER_INCLUDE_DIR})
